Assignment3/Models/Actor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace Assignment3.Models
{
    public class Actor
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string? Age { get; set; }
        public string? Gender { get; set; }
        public string? Hyperlink { get; set; }


        [DataType(DataType.Upload)]
        [DisplayName("Actor Image")]
        public byte[]? ActorImage { get; set; }
    }
}

Assignment3/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Assignment3.Data;
using Assignment3.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;
using System.Text.Json;
using VaderSharp2;

namespace TheMovieDB.Controllers
{
    public class ActorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public async Task<IActionResult> GetActorPhoto(int id)
        {
            var actor = await _context.Actor
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actor == null)
            {
                return NotFound();
            }
            var imageData = actor.ActorImage;

            return File(imageData, "image/jpg");
        }

        public ActorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Actors
        public async Task<IActionResult> Index()
        {
            return _context.Actor != null ?
                        View(await _context.Actor.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Actor'  is null.");
        }
        
        // START NEW CODE
        public static readonly HttpClient client = new HttpClient();
       
        public static string CategorizeSentiment(double sentiment)
        {
            if (sentiment >= -1 && sentiment < -0.6)
            {
                return "Extremely Negative";
            } else if (sentiment >= -.7 && sentiment < -0.2)
            {
                return "Very Negative";
            } else if (sentiment >= -.2 && sentiment < 0)
            {
                return "Slightly Negative";
            }  else if (sentiment >= 0 && sentiment < 0.2)
            {
                return "Slightly Positive";
            }  else if (sentiment >= 0.2 && sentiment < 0.6)
            {
                return "Very Positive";
            }  else if (sentiment >= 0.6 && sentiment < 1)
            {
                return "Extremely Positive";
            }
            else
            {
                return "Invalid Sentiment Value";
            }
        }
        public static async Task<List<string>> SearchWikipediaAsync(string searchQuery)
        {
            string baseUrl = "https://en.wikipedia.org/w/api.php";
            string url = $"{baseUrl}?action=query&list=search&srlimit=100&srsearch={Uri.EscapeDataString(searchQuery)}&format=json";
            List<string> textToExamine = new List<string>();
            try
            {
                //Ask WikiPedia for a list of pages that relate to the query
                HttpResponseMessage response = await client.GetAsync(url);
                response.EnsureSuccessStatusCode();
                string responseBody = await response.Content.ReadAsStringAsync();
                var jsonDocument = JsonDocument.Parse(responseBody);
                var searchResults = jsonDocument.RootElement.GetProperty("query").GetProperty("search");
                foreach (var item in searchResults.EnumerateArray())
                {
                    var pageId = item.GetProperty("pageid").ToString();
                    //Ask WikiPedia for the text of each page in the query results
                    string pageUrl = $"{baseUrl}?action=query&pageids={pageId}&prop=extracts&explaintext&format=json";
                    HttpResponseMessage pageResponse = await client.GetAsync(pageUrl);
                    pageResponse.EnsureSuccessStatusCode();
                    string pageResponseBody = await pageResponse.Content.ReadAsStringAsync();
                    var jsonPageDocument = JsonDocument.Parse(pageResponseBody);
                    var pageContent = jsonPageDocument.RootElement.GetProperty("query").GetProperty("pages").GetProperty(pageId).GetProperty("extract").GetString();
                    textToExamine.Add(pageContent);
                    
                }
            }
            catch (HttpRequestException e)
            {
                Console.WriteLine("\nException Caught!");
                Console.WriteLine("Message :{0} ", e.Message);
            }
            return textToExamine;
        }
        // END NEW CODE

        // GET: Actors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Actor == null)
            {
                return NotFound();
            }

            var actor = await _context.Actor
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actor == null)
            {
                return NotFound();
            }
            ActorDetailsVM ad = new ActorDetailsVM();
            ad.actor = actor;
            PostRating newPost = new PostRating();
            
            var movies = new List<Movie>();
            
            List<string> textToExamine = await SearchWikipediaAsync(actor.Name);
            newPost.text = textToExamine;
            
            
            // = await SearchWikipediaAsync((movie.Description));
            
            var analyzer = new SentimentIntensityAnalyzer();
            int validResults = 0;
            double resultsTotal = 0;
            List<double> tempList = new List<double>();
            
            foreach (string textValue in textToExamine)
            {
                var results = analyzer.PolarityScores(textValue);
                
                if (results.Compound != 0)
                {
                    tempList.Add(results.Compound);
                    resultsTotal += results.Compound;
                    validResults++;
                }
            }

            newPost.num = validResults;

            newPost.sentiment = tempList;
            
            double avgResult = Math.Round(resultsTotal / validResults, 2);
            ad.sentiment = avgResult.ToString() + ", " + CategorizeSentiment(avgResult);

            
            movies = await (from mt in _context.Movie
                join am in _context.ActorMovie on mt.Id equals am.Id
                where am.Id == id
                select mt).ToListAsync();
            ad.movies = movies;

            ad.postRatings = newPost;
 
            return View(ad);
        }

        // GET: Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Age,Gender,Hyperlink")] Actor actor, IFormFile ActorImage)
        {
            ModelState.Remove(nameof(actor.ActorImage));

            if (ModelState.IsValid)
            {
                if (ActorImage != null && ActorImage.Length > 0)
                {
                    var memoryStream = new MemoryStream();
                    await ActorImage.CopyToAsync(memoryStream);
                    actor.ActorImage = memoryStream.ToArray();
                }
                else
                {
                    actor.ActorImage = new byte[0];
                }
                _context.Add(actor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        //[Authorize(Roles = Constants.AdministratorsRole + "," + Constants.ManagersRole)]
        //[Authorize(Roles = "AdministratorRole,ManagerRole")] //this is an OR condition!!!
        //[Authorize(Roles = Constants.AdministratorsRole)]
        //[Authorize(Policy = Constants.ManagerAndAdministrator)]
        //[Authorize(Roles = Constants.Administrator + "," + Constants.Manager)]
        // GET: Actors/Edit/5
  
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Actor == null)
            {
                return NotFound();
            }

            var actor = await _context.Actor.FindAsync(id);
            if (actor == null)
            {
                return NotFound();
            }
            return View(actor);
        }

        // POST: Actors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Age,Gender,Hyperlink")] Actor actor, IFormFile ActorImage)
        {
            if (id != actor.Id)
            {
                return NotFound();
            }

            ModelState.Remove(nameof(actor.ActorImage));

            Actor existingActor = _context.Actor.AsNoTracking().FirstOrDefault(m => m.Id == id);

            if (ActorImage != null && ActorImage.Length > 0)
            {
                var memoryStream = new MemoryStream();
                await ActorImage.CopyToAsync(memoryStream);
                actor.ActorImage = memoryStream.ToArray();
            }
            //grab EXISTING photo from DB in case user didn't upload a new one. Otherwise, the actor will have the photo overwritten with empty
            else if (existingActor != null)
            {
                actor.ActorImage = existingActor.ActorImage;
            }
            else
            {
                actor.ActorImage = new byte[0];
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(actor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {

Assignment3/Views/Actors/Create.cshtml
@model Assignment3.Models.Actor

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Actor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hyperlink" class="control-label"></label>
                <input asp-for="Hyperlink" class="form-control" />
                <span asp-validation-for="Hyperlink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ActorImage" class="control-label"></label>
                <input type="file" id="ActorImage" name="ActorImage" multiple class="form-control" />
                <span asp-validation-for="ActorImage" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            <br>
        </form>
    </div>
</div>

<div>
    <button class="btn btn-light"><a class="black-text" asp-action="Index">Back to List</a></button>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Assignment3/Views/Actors/Delete.cshtml
@model Assignment3.Models.Actor

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Actor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hyperlink)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hyperlink)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ActorImage)
        </dt>
        <dd class = "col-sm-10">
                @if (Model.ActorImage != null && Model.ActorImage.Length != 0)
                {
                    <img height="150" src="@Url.Action("GetActorPhoto", "Actors", new {Model.Id})" />
                }
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <button class="btn btn-light"><a class="black-text" asp-action="Index">Back to List</a></button>
    </form>
</div>

Assignment3/Views/Actors/Details.cshtml
@model Assignment3.Models.ActorDetailsVM

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Actor</h4>
    <hr />
    
    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="@Url.Action("GetActorPhoto", "Actors", new {Model.actor.Id})" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">@Html.DisplayFor(model => model.actor.Name)</h5>
            <dl class="row">
                <dt class = "col-sm-5">
                    @Html.DisplayNameFor(model => model.actor.Age)
                </dt>
                <dd class = "col-sm-5">
                    @Html.DisplayFor(model => model.actor.Age)
                </dd>
                <dt class = "col-sm-5">
                    @Html.DisplayNameFor(model => model.actor.Gender)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.actor.Gender)
                </dd>
                <dt class = "col-sm-5">
                    @Html.DisplayNameFor(model => model.actor.Hyperlink)
                </dt>
                <dd class="col-sm-10">
                    <a target="_blank" href="@Html.DisplayFor(model => model.actor.Hyperlink)">IMDb</a>
                </dd>
                <dt class = "col-sm-5">
                    Sentiment
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.sentiment)
                </dd>
            </dl>
        </div>
    </div>
</div>
<br>
<div>
    <button class="btn btn-light"><a class="black-text" asp-action="Edit" asp-route-id="@Model?.actor.Id">Edit</a></button>
    <button class="btn btn-light"><a class="black-text" asp-action="Index">Back to List</a></button>
</div>

<br />
<h1>
    Movies with @Html.DisplayFor(model => model.actor.Name)
</h1>
<table id="indexTable" class="table">
    <thead>
    <tr>
        <th>
            Title
        </th>
        <th>
            Description
        </th>
        <th>
            Director
        </th>
        <th>
            Genre
        </th>
        <th>
            Release Year
        </th>
        <th>
            Hyperlink
        </th>
        <th>
            Movie Image
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.movies)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Director)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                <a target="_blank" href="@Html.DisplayFor(modelItem => item.Hyperlink)">IMDb</a>
            </td>
            <td>
                @if (item.MovieImage != null && item.MovieImage.Length != 0)
                {
                    <img height="150" src="@Url.Action("GetMoviePhoto", "Movies", new {item.Id})" />
                }
            </td>
            <td>
                    
                <button class="btn btn-light" asp-action="Edit" asp-controller="Movies" asp-route-id="@item.Id"><a class="black-text" asp-action="Edit" asp-controller="Movies" asp-route-id="@item.Id">Edit</a></button>
                <button class="btn btn-light" asp-action="Details" asp-controller="Movies" asp-route-id="@item.Id"><a class="black-text" asp-action="Details" asp-controller="Movies" asp-route-id="@item.Id">Details</a></button>
                @* <a asp-action="Edit" asp-controller="Movies" asp-route-id="@item.Id">Edit</a> | *@
                @* <a asp-action="Details" asp-controller="Movies" asp-route-id="@item.Id">Details</a> | *@
            </td>
        </tr>
    }
    </tbody>
</table>
<table id="indexTable2" class="table">
    <thead>
    <tr>
        <th>
            Post
        </th>
        <th>
            Sentiment
        </th>
    </tr>
    </thead>
    <tbody>
    <h1>Wikipedia Posts Referencing @Html.DisplayFor(model => model.actor.Name) </h1>
    @for (int i = 0; i < Model.postRatings.num; i++)
    {
        <tr>
            <td>
                @Model.postRatings.text[i]
            </td>
            <td>
                @Model.postRatings.sentiment[i]
            </td>
        </tr>
    }
    </tbody>
</table>
@section Scripts {
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.1/css/dataTables.dataTables.min.css" integrity="sha384-zUxWDVAcow8yNu+q4VFsyZA3qWsKKGdWPW0SVjaR12LQze4SY8Nr75US6VDhbWkf" crossorigin="anonymous">
    <script src="https://cdn.datatables.net/2.0.1/js/dataTables.min.js" integrity="sha384-O1CwIpQyArpIVIf/MmRsfivHkHhSlKgnk+wOxIMeEqObjH8MoV/Ox0ue6FlCwucf" crossorigin="anonymous"></script>
    <script>
            $(document).ready(function() {
                $('#indexTable').DataTable();
                $('#indexTable2').DataTable();
            });
    </script>
}

Assignment3/Views/Actors/Edit.cshtml
@model Assignment3.Models.Actor

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Actor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hyperlink" class="control-label"></label>
                <input asp-for="Hyperlink" class="form-control" />
                <span asp-validation-for="Hyperlink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ActorImage" class="control-label"></label>
                <input type="file" id="ActorImage" name="ActorImage" multiple class="form-control" />
                <span asp-validation-for="ActorImage" class="text-danger"></span>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br>
<div>
    <button class="btn btn-light"><a class="black-text" asp-action="Index">Back to List</a></button>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Assignment3/Views/Actors/Index.cshtml
@model IEnumerable<Assignment3.Models.Actor>

@{
    ViewData["Title"] = "Index";
}

<h1>Actors</h1>

<p>
    <button class="btn btn-light"><a class="black-text" asp-action="Create">Create New</a></button>
</p>
<table id="indexTable" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Hyperlink)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ActorImage)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                <a target="_blank" href="@Html.DisplayFor(modelItem => item.Hyperlink)">IMDb</a>
            </td>
                <td>
                    @if (item.ActorImage != null && item.ActorImage.Length != 0)
                    {
                        <img height="150" src="@Url.Action("GetActorPhoto", "Actors", new {item.Id})" />
                    }
                </td>
                <td>
                <button class="btn btn-light" asp-action="Details" asp-route-id="@item.Id"><a class="black-text" asp-action="Details" asp-route-id="@item.Id">Details</a></button>
                <button class="btn btn-light" asp-action="Edit" asp-route-id="@item.Id"><a class="black-text" asp-action="Edit" asp-route-id="@item.Id">Edit</a></button>
                <button class="btn btn-light" asp-action="Delete" asp-route-id="@item.Id"><a class="black-text" asp-action="Delete" asp-route-id="@item.Id">Delete</a></button>
                    @* <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> | *@
                    @* <a asp-action="Details" asp-route-id="@item.Id">Details</a> | *@
                    @* <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> *@
                </td>
        </tr>
}
    </tbody>
</table>
@section Scripts {
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.1/css/dataTables.dataTables.min.css" integrity="sha384-zUxWDVAcow8yNu+q4VFsyZA3qWsKKGdWPW0SVjaR12LQze4SY8Nr75US6VDhbWkf" crossorigin="anonymous">
    <script src="https://cdn.datatables.net/2.0.1/js/dataTables.min.js" integrity="sha384-O1CwIpQyArpIVIf/MmRsfivHkHhSlKgnk+wOxIMeEqObjH8MoV/Ox0ue6FlCwucf" crossorigin="anonymous"></script>
    <script>let table = new DataTable('#indexTable');</script>
}